name: Rust Lambda Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup-ecr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - id: commit
      uses: pr-mpt/actions-commit-hash@v2
    - name: Install CDKTF CLI
      run: yarn global add cdktf-cli
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.1
        terraform_wrapper: false
    - name: Set up cdktf cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          infra/node_modules/
          infra/.gen/
          infra/cdktf.out/
        key: ${{ runner.os }}-cdktf-${{ hashFiles('infra/**/yarn.lock', '**/constraints.json') }}
    - name: Setup ECR
      working-directory: infra
      run: |
        yarn install --frozen-lockfile --prefer-offline
        terraform version -json
        cdktf get
        cdktf deploy ecr --auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        COMMIT_SHA: ${{ steps.commit.outputs.short }}

  build-and-test:
    runs-on: ubuntu-latest
    needs:
      - setup-ecr
    services:
      postgres:
        image: "postgres:14"
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DATABASE: testdb

    steps:
    - uses: actions/checkout@v3
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/            
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: BinInstall Cargo SQLX CLI
      run: (curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash) && cargo binstall --no-confirm --no-symlinks sqlx-cli
    - name: Build
      run: cargo build --verbose
    - name: Create DB
      run: sqlx db create
      env:
        DATABASE_URL: postgres://postgres:password@localhost/postgres?sslmode=disable
    - name: Run tests
      run: cargo test --verbose
      env:
        DATABASE_URL: postgres://postgres:password@localhost/postgres?sslmode=disable
    - uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - id: commit
      uses: pr-mpt/actions-commit-hash@v2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: true
        provenance: false
        tags: ${{ secrets.ECR_REPO_URL }}:${{ steps.commit.outputs.short }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
